### ISSUE TITLE
Testing on a video

### ISSUE THREAD

**Issue by Morceguito** [mullisd1/CV_Heartrate#2]
What is the script that I should use to teste this implementation on a single video and obtain the heartrate for that video?

**Comment by qiuqidrone** [comment]
Have you tested your own videos by the code? Can we talk about it?

**Comment by davidhaas6** [comment]
@qiuqidrone I'd talk about it. Add me on discord: davinki#9135

**Comment by davidhaas6** [comment]
@Morceguito 
`python3 bvp.py --draw --source ./video.mp4`
We don't have a requirements.txt so you'll have to manually install the dependencies.
